server:
  port: 8080
  servlet:
    context-path: /saa

logging:
  config: classpath:log/logback.cfg.xml

saa:
  browser:
    loginPage: /default-form-image-code-sign-in.html
    loginProcessingUrl: /authentication/form
  validateCode:
    imageCode:
      width: 67
      height: 23
      codeLength: 4
      expiredInMinutes: 5
    smsCode:
      codeLength: 6
      expiredInMinutes: 5
