server:
  port: 8080
  servlet:
    context-path: /saa

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saa?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: lotus

saa:
  browser:
    loginPage: /default-form-sign-in.html
    loginProcessingUrl: /authentication/form
    rememberMeSeconds: 30